# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Reaction Seminar"
description: "Reaction Seminar is a set of seminars in the field of nuclear reactions"
baseurl: "/"
url: "reactionseminar.github.io"
permalink: "/blog/:title"
googleAnalyticsSiteUrl: "reactionseminar.github.io"


# Head
metaKeywords: "Nuclear reaction, Quantum scattering, Fusion"



# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
#bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Reaction <typeout> Seminar"
eventDate: "March - May, 2020"
typeoutTextValues: '"", "Scattering", "Fusion","brekup","transfer","knockout","stripping"'


# About Block
aboutTitle: "About Reaction Seminar"
aboutText1: "For the special time period of COVID-19, we would like to organize a 
series of online seminars that everybody can join. The seminars will cover all the fields of nuclear reaction with 
special emphasize on the description and interpretation of different types of direct reactions: elastic/inelastic scattering,
breakup, quasi-free (p,pN) processes, charge-exchange, … "

aboutText2: "The seminar will be held every XXXday at XX time"




